// Granular permission codes (SRS section 41) grouped by module.
// Roles are assigned permissions rather than having access hard-coded (SRS: "Roles shall be
// assigned permissions rather than hard-coded throughout the application").

const PERMISSIONS = {
  // Users / roles / system administration
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
  MANAGE_LOCATIONS: 'MANAGE_LOCATIONS',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',

  // Product / catalog
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  CREATE_PRODUCTS: 'CREATE_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',

  // Inventory
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  ADJUST_INVENTORY: 'ADJUST_INVENTORY',
  APPROVE_ADJUSTMENT: 'APPROVE_ADJUSTMENT',
  CONDUCT_STOCK_COUNT: 'CONDUCT_STOCK_COUNT',
  APPROVE_STOCK_COUNT: 'APPROVE_STOCK_COUNT',

  // Transfers
  REQUEST_TRANSFER: 'REQUEST_TRANSFER',
  APPROVE_TRANSFER: 'APPROVE_TRANSFER',
  ISSUE_TRANSFER: 'ISSUE_TRANSFER',
  RECEIVE_TRANSFER: 'RECEIVE_TRANSFER',

  // Purchasing
  CREATE_PURCHASE: 'CREATE_PURCHASE',
  APPROVE_PURCHASE: 'APPROVE_PURCHASE',
  RECEIVE_STOCK: 'RECEIVE_STOCK',

  // POS / Sales
  OPEN_POS_SESSION: 'OPEN_POS_SESSION',
  CREATE_SALE: 'CREATE_SALE',
  VOID_SALE: 'VOID_SALE',
  REFUND_SALE: 'REFUND_SALE',
  APPLY_DISCOUNT: 'APPLY_DISCOUNT',
  OVERRIDE_STOCK_CHECK: 'OVERRIDE_STOCK_CHECK',

  // Reports
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  VIEW_FINANCIALS: 'VIEW_FINANCIALS',
};

// Default role -> permission mapping seeded on first run (SRS section 4).
const ROLE_PERMISSIONS = {
  'Super Administrator': Object.values(PERMISSIONS),
  'Inventory Manager': [
    PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.CREATE_PRODUCTS, PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.MANAGE_CATEGORIES, PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_INVENTORY, PERMISSIONS.ADJUST_INVENTORY, PERMISSIONS.APPROVE_ADJUSTMENT,
    PERMISSIONS.CONDUCT_STOCK_COUNT, PERMISSIONS.APPROVE_STOCK_COUNT,
    PERMISSIONS.REQUEST_TRANSFER, PERMISSIONS.APPROVE_TRANSFER, PERMISSIONS.ISSUE_TRANSFER, PERMISSIONS.RECEIVE_TRANSFER,
    PERMISSIONS.CREATE_PURCHASE, PERMISSIONS.APPROVE_PURCHASE, PERMISSIONS.RECEIVE_STOCK,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.EXPORT_REPORTS, PERMISSIONS.MANAGE_LOCATIONS,
  ],
  'Warehouse Officer': [
    PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.RECEIVE_STOCK, PERMISSIONS.ISSUE_TRANSFER, PERMISSIONS.RECEIVE_TRANSFER, PERMISSIONS.REQUEST_TRANSFER,
    PERMISSIONS.CONDUCT_STOCK_COUNT, PERMISSIONS.VIEW_REPORTS,
  ],
  'Shop Manager': [
    PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.VIEW_INVENTORY, PERMISSIONS.REQUEST_TRANSFER, PERMISSIONS.RECEIVE_TRANSFER,
    PERMISSIONS.CONDUCT_STOCK_COUNT, PERMISSIONS.REFUND_SALE, PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.OPEN_POS_SESSION, PERMISSIONS.CREATE_SALE,
  ],
  'Cashier': [
    PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.OPEN_POS_SESSION, PERMISSIONS.CREATE_SALE, PERMISSIONS.APPLY_DISCOUNT,
  ],
  'Accountant': [
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.EXPORT_REPORTS, PERMISSIONS.VIEW_FINANCIALS,
  ],
  'Auditor': [
    PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.VIEW_INVENTORY, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.VIEW_AUDIT_LOG,
  ],
};

// Default max discount percentage a role may apply without manager approval (SRS section 30).
const ROLE_DISCOUNT_LIMIT = {
  'Super Administrator': 100,
  'Inventory Manager': 20,
  'Shop Manager': 15,
  'Cashier': 5,
  'Warehouse Officer': 0,
  'Accountant': 0,
  'Auditor': 0,
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, ROLE_DISCOUNT_LIMIT };
